#!/bin/bash

SRC=src
DIST=dist
DOMAIN=geheimesite.nl

BUILD="bun -b run eleventy"
FORMAT="prettier --ignore-path .prettierignore"
DEPLOY="$DEPLOY --exclude canvas.json --exclude js0.23 --exclude r"

build() {
  $BUILD
}

serve() {
  $BUILD --serve --port 4000
}

deploy() {
  if [ -d $DIST ]; then
    $DEPLOY $DIST/ s11:domains/$DOMAIN/public_html
    $DEPLOY $DIST/ nov:/volume1/www/$DOMAIN
    $DEPLOY $DIST/ nov:/volume1/www/november.geheimesite.nl
  else
    err "'$DIST' does not exist."
  fi
}

clean() {
  rm -rf $DIST
}
