#!/usr/bin/env bash

use elixir

SRC=src
DIST=dist
HOST=geheimesite.nl

export FORMAT="prettier --ignore-path .prettierignore"
export VALIDATE="vnu --exit-zero-always --filterfile .vnuignore"

setup() {
  required elixir
  required npm
  required lightningcss
  required pandoc
  required fswatch
  required prettier
  required stylelint
  required achecker
  required vnu

  p:step "Fetching dependencies"; quiet mix deps.get && p:done
  p:step "Compiling dependencies"; quiet mix deps.compile && p:done

  p:step "Installing npm dependencies"

  while read -r package; do
    [ -f "$package" ] || continue
    quiet npm ci --prefix "${package%/*}"
  done < <(git ls-files -co --exclude-standard ':(glob)**/package.json')

  p:done
}

build() {
  required lightningcss
  required pandoc

  mix compile "$@"
}

watch() {
  required fswatch

  fswatch src lib priv | while read; do build; done
}

serve() {
  build # Perform a full build first
  export -f $(compgen -A function)
  spawn "cheese -p 4000 $DIST/${1:-$HOST}" watch
}

clean() {
  mix clean
  rm -rf $DIST results
  git restore-mtime >/dev/null 2>&1
}

check() {
  p:step "Running formatter"
  $FORMAT --check $DIST --log-level warn && p:great

  p:step "Running validators"
  $VALIDATE --skip-non-html $DIST && p:great
  
  p:step "Running stylelint"
  stylelint "$SRC/**/*.css" && p:great

  p:step "\nRunning achecker"; printf "\n"
  achecker $DIST && p:great

  # BLOCKED: htmltest doesn't yet support pretty URLs like I have,
  # see https://github.com/wjdp/htmltest/issues/183

  # echo
  # p:step "Running htmltest"
  # htmltest && p:great
}

purge() {
  required curl
  required pass

  ZONE=3135921
  TOKEN=$(pass show tokens/bunny)

  p:step "Purging CDN cache"
  curl -fsS -o /dev/null -X POST \
    "https://api.bunny.net/pullzone/$ZONE/purgeCache" \
    -H "AccessKey: $TOKEN" \
    -H "Content-Type: application/json" && p:done
}

# Helper functions for nice terminal output

p:step() {
  if [ -z "${RECIPE_SILENT:-}" ]; then
    printf "$1... "
  fi
}

p:great() {
  p:good "no issues"
}

p:done() {
  p:good "done"
}

p:good() {
  case "${NO_COLOR:-}" in
    ""|0)
      GREEN="\033[1;32m"
      CLEAR="\033[0m"
  esac

  printf "${GREEN:-}$1${CLEAR:-}\n"
}
