baseURL: https://geheimesite.nl/
title: Robin Boers
defaultContentLanguage: nl
timeZone: Europe/Amsterdam
enableEmoji: true
enableRobotsTXT: true

minify:
    disableHTML: true
    minifyOutput: true

languages:
    nl:
        contentDir: content/nl
        languageName: Nederlands
        languageCode: nl
        params:
            copyright: Webdesigner en Elixir programmeur sinds 2017.
        menu:
            main:
                - identifier: blog
                  name: Blog
                  url: https://blog.geheimesite.nl
                  weight: 6
            homepage:
                - identifier: neolog
                  name: Neolog
                  url: https://micro.geheimesite.nl
                  weight: 2
                - identifier: ckv
                  name: CKV
                  url: /ckv
                  weight: 3
                - identifier: github
                  name: GitHub
                  url: https://github.com/RobinBoers
                  weight: 4

    en:
        contentDir: content/en
        languageName: English
        languageCode: en
        params:
            copyright: Webdesigner and Elixir programmer since 2017.
        menu:
            main:
                - identifier: blog
                  name: Blog
                  url: https://blog.geheimesite.nl/en
                  weight: 6
            homepage:
                - identifier: neolog
                  name: Neolog
                  url: https://micro.geheimesite.nl
                  weight: 2
                - identifier: ckv
                  name: CKV
                  url: /ckv
                  weight: 3
                - identifier: github
                  name: GitHub
                  url: https://github.com/RobinBoers
                  weight: 4

markup:
    goldmark:
        renderer:
            unsafe: true

disableKinds:
    - sitemap
    - RSS
