baseURL: https://geheimesite.nl/
title: Robin Boers
defaultContentLanguage: nl
timeZone: Europe/Amsterdam
enableEmoji: true
theme: spockle

author:
    name: Robin Boers
    image: https://geheimesite.nl/images/me_optimized.jpeg
    about: I'm a webdesigner, programmer, and nerd living in the Netherlands. I'm 15 years old and I currently work at Qdentity.

publishDir: dist
themesDir: src/themes

module:
    mounts:
        - source: src
          target: assets
          includeFiles: assets/**/*
        - source: src/static
          target: static
        - source: src/layouts
          target: layouts
        - source: src/data
          target: data

minify:
    disableHTML: true
    minifyOutput: true

languages:
    nl:
        contentDir: src/content/nl
        languageName: Nederlands
        languageCode: nl
        copyright: Webdesigner en Elixir programmeur sinds 2017.
        params:
            description: Ik ben een webdesigner, tiener en nerd die in Maassluis woont. M'n hobby's zijn programmeren, video-editten, handbal (ik ben keeper) en tekenen. Ik ben 15 jaar oud en ik werk bij Qdentity. Ik vind het leuk om websites en apps te ontwikkelen en ik vind het fantastisch om met Linux te kloten.
        menu:
            main:
                - identifier: blog
                  name: Blog
                  url: https://blog.geheimesite.nl
                  weight: 6
            homepage:
                - identifier: hyperfeed
                  name: Hyperfeed
                  url: /hyperfeed
                  weight: 1
                - identifier: neolog
                  name: Neolog
                  url: https://micro.geheimesite.nl
                  weight: 2
                - identifier: ckv
                  name: CKV
                  url: /ckv
                  weight: 3
                - identifier: github
                  name: GitHub
                  url: https://github.com/RobinBoers
                  weight: 4

    en:
        contentDir: src/content/en
        languageName: English
        languageCode: en
        copyright: Webdesigner and Elixir programmer since 2017.
        params:
            description: I'm webdesigner, teenager and nerd living in the Netherlands. My hobbies are programming and handball. I'm 15 years old and I currently work at Qdentity. I enjoy building websites and apps in my free time, and I love to thinker with Linux.
        menu:
            main:
                - identifier: blog
                  name: Blog
                  url: https://blog.geheimesite.nl/en
                  weight: 6
            homepage:
                - identifier: neolog
                  name: Neolog
                  url: https://micro.geheimesite.nl
                  weight: 2
                - identifier: ckv
                  name: CKV
                  url: /ckv
                  weight: 3
                - identifier: github
                  name: GitHub
                  url: https://github.com/RobinBoers
                  weight: 4

markup:
    goldmark:
        renderer:
            unsafe: true

enableRobotsTXT: false
disableHugoGeneratorInject: true
disableKinds:
    - sitemap
    - RSS
    - section
    - term
    - taxonomy
