#!/bin/sh -eu

EXT="html"

printf "\nTitle: "
read TITLE

if [ "$TITLE" = "" ]; then
  echo >&2 "Error: you didn't provide a title"
  echo >&2
  exit 1
fi

printf "\nLanguage [en]: "
read LANG

if [ "$LANG" = "" ]; then
  LANG="en"
  echo "(Using '$LANG' as default language)"
fi

printf "\nPath [slug]: "
read path

sluggify() { echo "$1" | tr '[:upper:]' '[:lower:]' | tr -cs '[:alnum:]' '-' | sed 's/-$//'; }

if [ "$path" = "" ]; then
  path="$(sluggify "$TITLE").$EXT"
  echo "(Using autogenerated '$path')"
  echo
fi

if [ -e "$path" ]; then
  echo >&2 "Error: file '$path' already exists."
  echo >&2 
  exit 1
fi

export TITLE
export LANG
export URL="$(basename "$path" ".$EXT")"

cat TEMPLATE.html | envsubst > "$path" 
e "$path"
