#!/bin/bash

use elixir

ASSETS="$(pwd)/assets"
PUBLIC="$(pwd)/public"
DIST="$(pwd)/dist"

setup() {
	super

	npm install --prefix $ASSETS
}

build() {
	super

	mix popcorn.cook
  npm run build --prefix "$ASSETS"
	cp $PUBLIC/Caddyfile $DIST
}

serve() {
	spawn "mix popcorn.server" \
				"npm run watch --prefix "$ASSETS""
}

deploy() {
	lift deploy
}
