on: 
  push:
    branches: [ master ]
name: Deploy website via FTP
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        dry-run: true
        server-dir: domains/geheimesite.nl/public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          library/website/version/*
